name: CAPP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip=25.2
  - ipykernel=6.30.1
  - papermill=2.6.0
  
  # Essential packages from notebooks
  - numpy=2.1.3
  - pandas=2.3.2
  - scipy=1.15.3
  - matplotlib=3.10.5
  - seaborn=0.13.2
  - scikit-learn=1.7.1
  - pytorch=2.6.0
  - jupyter=1.1.1
  - jupyterlab=4.4.6
  - networkx=3.4.2
  - tqdm=4.67.1
  
  - pip:
      - hetmatpy==0.1.0
      - hetnetpy==0.3.1
