#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from scripts.repro.common import repo_root, write_run_summary, ensure_file_exists


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create Figure 1 reference note artifact.")
    parser.add_argument("--data-dir", type=Path, default=repo_root() / "data")
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=repo_root() / "results" / "repro" / "figures",
    )
    parser.add_argument("--random-seed", type=int, default=42)
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--skip-plots", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_file = args.results_dir / "fig1_reference_note.md"
    output_file.parent.mkdir(parents=True, exist_ok=True)

    output_file.write_text(
        "# Figure 1 Reference\n\n"
        "Figure 1 is a reference to prior DWPC degree-pattern work and is not "
        "generated by this repository.\n",
        encoding="utf-8",
    )
    ensure_file_exists(output_file)

    write_run_summary(
        args.results_dir / "repro_fig1_reference_run_summary.json",
        args,
        extra={"output_file": output_file},
    )


if __name__ == "__main__":
    main()
