#!/bin/bash
#SBATCH --job-name=ceiling_analysis
#SBATCH --output=logs/ceiling/%A/task_%a.out
#SBATCH --error=logs/ceiling/%A/task_%a.err
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --array=1-119
#SBATCH --partition=amilan

# Phase 1: Ceiling Analysis - HPC Array Job
# Runs oracle upper bound, binning resolution, and feature sufficiency
# for all 119 2-hop metapaths in parallel.
#
# Submit with: sbatch scripts/phase1_ceiling_analysis_array.sh
#
# Results: results/ceiling_analysis/{metapath}/
#   - oracle_exact_r.txt
#   - oracle_binned_r.txt
#   - binning_resolution.csv
#   - feature_sufficiency.csv
#   - ceiling_analysis_results.pkl
#   - summary.txt

# Activate conda environment
source /curc/sw/anaconda3/latest
conda activate CAPP

# Create logs directory organized by job ID
mkdir -p logs/ceiling/${SLURM_JOB_ID}

# Load metapath list (generated by src/metapath_utils.py)
METAPATH_FILE="data/2hop_metapaths.txt"

if [ ! -f "$METAPATH_FILE" ]; then
    echo "ERROR: Metapath list not found at $METAPATH_FILE"
    echo "Run: python src/metapath_utils.py"
    exit 1
fi

# Get metapath for this array task
METAPATH=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "$METAPATH_FILE" | cut -f1)

if [ -z "$METAPATH" ]; then
    echo "ERROR: Could not read metapath for array task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

# Create symlinks with metapath names for easier identification
ln -sf task_${SLURM_ARRAY_TASK_ID}.out logs/ceiling/${SLURM_JOB_ID}/${METAPATH}.out
ln -sf task_${SLURM_ARRAY_TASK_ID}.err logs/ceiling/${SLURM_JOB_ID}/${METAPATH}.err

echo "========================================================================"
echo "SLURM Job ID: $SLURM_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"
echo "Metapath: $METAPATH"
echo "Node: $SLURM_NODELIST"
echo "========================================================================"

# Run ceiling analysis for this metapath
# Training: Original Hetionet (data/)
# Testing: Permutations 0-19 (data/permutations/)
python run_phase1_ceiling_single_metapath.py \
    --metapath "$METAPATH" \
    --data_dir data \
    --perm_dir data/permutations \
    --output_dir results/ceiling_analysis \
    --test_start 0 \
    --test_end 20 \
    --n_bins 10

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo "SUCCESS: Ceiling analysis completed for $METAPATH"
else
    echo "ERROR: Ceiling analysis failed for $METAPATH (exit code: $EXIT_CODE)"
fi

exit $EXIT_CODE
